#ifndef __CODE_H_
#define __CODE_H_

typedef enum
{
	ZERO_CODE,
	SUCCESS_LOGIN,
	SUCCESS_LOGOUT,
	SUCCESS_CREATE_ACCOUNT,
	SUCCESS_CREATE_GROUP,
	SUCCESS_ADD_USER,
	SUCCESS_SEND_MESSAGE,
	FAIL_LOGIN,
	FAIL_LOGOUT,
	FAIL_CREATE_ACCOUNT,
	FAIL_CREATE_GROUP,
	FAIL_ADD_USER,
	FAIL_SEND_MESSAGE
}CodeNum;

#endif