#!/bin/bash

cd lib/libfdr/
make clean
make all
cd ..
cd libllist/
make clean
make all
cd ..
cd libgraph/
make clean
make all
cd ..
cd libabs/
make clean
make all
cd ..
cd bt\-5.0.0
make clean
make all
cd ..
cd libstring/
make clean
make all
cd ..
cd libnetwork/
cd ent_config
make clean
make all
cd ../io_config
make clean
make all
cd ../pro_config
make clean
make all
cd ../socket_api
make clean
make all
cd

